Documentation updates for document version 2.0.0
GIDSOpenStandaarden/GIDS-HTI-Protocol pull request #23
Opened 2023-01-30 16:34 UTC by rolandgroen

- fixes #18, update documentation.

2023-02-16 13:21 UTC, rolandgroen commented on HTI_2.0.md
> +Based on the changes above, the mapping between the fields is as follows:
Will add.

2023-02-17 09:52 UTC, JorisHeadease requested changes

2023-02-17 09:52 UTC, JorisHeadease commented on HTI_2.0.md
> +| The fields used in the HTI claims object MUST match the table HTI claims field mapping. |
Er is geen kopje dat "HTI claims field mapping" heet, kan duidelijker zijn waar naar gerefereerd wordt. En "match" is misschien niet de juiste term aangezien er optionele velden zijn. Misschien "conform" ② The message format?

2023-02-17 09:52 UTC, JorisHeadease commented on HTI_2.0.md
> + | The user identifier (`sub` field) MUST be used for the user that should execute the task. |
`sub` zal in veel gevallen juist niet de taak uitvoeren maar beoordelen. Wordt hier `patient` bedoeld?

2023-02-17 09:52 UTC, JorisHeadease commented on HTI_2.0.md
> +## The portal application
Er mist een eis over het zetten van de HTI versie in de header

2023-02-17 09:52 UTC, JorisHeadease commented on HTI_2.0.md
> + | The fields used in the JWT payload MUST match the table JWT field mapping. |
Is dit niet hetzelfde als de bovenstaande eis?

> The fields used in the HTI claims object MUST match the table HTI claims field mapping.

2023-02-17 09:52 UTC, JorisHeadease commented on HTI_2.0.md
> + | The JWT token MUST be exchanged over an encrypted http (https) connection. |
Willen we nog restricties leggen aan de TLS versie?

2023-03-09 13:36 UTC, janwijbrand commented on CHANGELOG.md
>  ## HTI:core version 1.1
the following changes are cosmetics only. Perhaps they can be commited to master already which would make the PR easier to read.

2025-01-29 09:03 UTC, rolandgroen commented on HTI_2.0.md
> +In most cases, tasks will be assigned to a `Patient`. We advise to use the `Person` type if unsure about the resource type of the `sub` field.
Ja, in bijvoorbeeld een wijkplatform.

2025-01-29 09:06 UTC, rolandgroen commented on HTI_2.0.md
> + | The user identifier (`sub` field) MUST be used for the user that should execute the task. |
Ik zie wat verwarring rond de "taak uitvoeren". In mijn beperkte wereldbeeld is zoiets als "meekijken"., "inzien" en "beoordelen" op een taak op zich. Hoewel gerelateerd aan de hoofdtaak.

2025-01-29 09:42 UTC, merged